 <!-- Filename: /module/Blog/view/blog/write/add.phtml -->
 <h1>step</h1>
   <?php
  
 $form = $this->form;
 $form->setAttribute('action', $this->url($this->route, array('step' => $this->nextstep)));
 $form->prepare();

 echo $this->form()->openTag($form);

 echo $this->formCollection($form);

 echo $this->form()->closeTag();
 //$test = array('action' => 'loadform'.$this->nextstep)
echo 'loadform'.$this->nextstep;